"""campaign target shuffle chamber

Revision ID: 3254c70a6f37
Revises: f8e4f3786603
Create Date: 2018-01-11 14:53:00.218981

"""

# revision identifiers, used by Alembic.
revision = '3254c70a6f37'
down_revision = 'f8e4f3786603'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_shuffle_chamber', sa.Boolean(), nullable=True, server_default='1'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.drop_column('target_shuffle_chamber')
    ### end Alembic commands ###
