"""sync_crm_key

Revision ID: cdd4c25989d6
Revises: 3b2f5b729b7a
Create Date: 2019-05-09 15:01:06.445559

"""

# revision identifiers, used by Alembic.
revision = 'cdd4c25989d6'
down_revision = '3b2f5b729b7a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crm_key', sa.String(length=40), nullable=True))
        batch_op.create_unique_constraint(None, ['campaign_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_campaign', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('crm_key')

    # ### end Alembic commands ###
