# User roles
SCHEDULE_NIGHTLY = 'nightly'
SCHEDULE_HOURLY = 'hourly'
SCHEDULE_IMMEDIATE = 'immediate'
SCHEDULE_CHOICES = {
    SCHEDULE_NIGHTLY: SCHEDULE_NIGHTLY.capitalize(),
    SCHEDULE_HOURLY: SCHEDULE_HOURLY.capitalize(),
    SCHEDULE_IMMEDIATE: SCHEDULE_IMMEDIATE.capitalize(),
}
