name: Tests

on:
  push:
    branches: ["work"]
  pull_request:
    branches: ["work"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements/development.txt
      - name: Test with pytest
        run: |
          pytest -m "not slow" --cov=call_server/
